### ISSUE TITLE
Leider kein Quellcode

### ISSUE THREAD

**Issue by hamburger123456** [mecodia/check-dein-passwort#5]
Hallo, Ich kann leider nirgens lesbaren Quellcode finden. (alles nur uglyfied)
Ist das Absicht?

**Comment by toabi** [comment]
Das wird alles aus den .coffee files gebaut.

**Comment by Fohlen** [comment]
Hallo @hamburger123456, leider stimmt das nicht so ganz. Wenn du in den Ordner `web` navigierst wirst du den entsprechenden Quellcode finden.

**Comment by hamburger123456** [comment]
Sorry, aber die Datei https://github.com/mecodia/check-dein-passwort/blob/master/web/public/js/app.js zeigt uglyfied Javascript.
In den .coffee-files finde ich den javascript-code auch nicht.

**Comment by Fohlen** [comment]
https://github.com/mecodia/check-dein-passwort/blob/master/web/app/app.coffee

**Comment by hamburger123456** [comment]
Hallo Fohlen,
sei mir bitte nicht böse, aber in der genannten app.coffee steht was ganz anderes. Ich kann nirgendwo eine Datei finden die z.B. die Deklaration von passwords.names enthält, außer in der von mir zitierten uglyfied-Datei.

**Comment by Fohlen** [comment]
https://github.com/mecodia/check-dein-passwort/blob/ef2894fa4c6ddb872a04aea43701a460c60b18da/cdplib/src/passwords/names.coffee

**Comment by hamburger123456** [comment]
Vielen Dank Fohlen,
das war nur ein Beispiel, ein schlechtes zugegeben. Ich suche eigentlich den klaren Inhalt der Datei https://github.com/mecodia/check-dein-passwort/blob/master/web/public/js/app.js
Diese liegt nur uglyfied vor.

**Comment by Fohlen** [comment]
@hamburger123456 wie @toabi schon anmerkte ist die Anwendung in [coffeeScript](http://coffeescript.org/) und nicht in JavaScript geschrieben.

**Comment by toabi** [comment]
Jo. Und wird mit Brunch zusammengesteckt. Ich empfehle mal die READMEs anzuschauen. Es ist in lib und Web getrennt da es früher auch mal ne mobile hybrid App gab.
